# Generated by Django 5.1.4 on 2024-12-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=30)),
                ('venue', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], default='Home', max_length=4)),
                ('date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='darts.seasons')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
